### ISSUE TITLE
Infinite loop on circular registry

### ISSUE THREAD

**Issue by sbv-csis** [williballenthin/python-registry#57] opened 2015-12-21 14:53 UTC
We see some registry with circular references resulting in infinite loop while trying to throw a RegistryKeyKeyNotFound exception (version https://pypi.python.org/packages/source/p/python-registry/python-registry-1.1.0a.tar.gz#md5=589311e55826174c1d50b0b177cd9d55)
```
    key = root.subkey("Select")
  File "/opt/python2.7/lib/python2.7/site-packages/Registry/Registry.py", line 249, in subkey
    raise RegistryKeyNotFoundException(self.path() + "\\" + name)
  File "/opt/python2.7/lib/python2.7/site-packages/Registry/Registry.py", line 209, in path
    return self._nkrecord.path()
  File "/opt/python2.7/lib/python2.7/site-packages/Registry/RegistryParse.py", line 1232, in path
    name = p.name() + "\\" + name
KeyboardInterrupt
```
If I add a print ('name', name) at line 1232 I see this:
``` 
name CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
name Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}\Microsoft\Windows\CMI-CreateHive{3D971F19-49AB-4000-8D39-A6D9C673D809}
....
```
worse and worse until I run out of memory

**Comment by NiKiZe** [comment] 2015-12-21 18:46
Should there be some kind of lookup table for offset pointing to decoded key, if any parent already contains that node what should it do?

Best way to generate an hive to reproduce this?

**Comment by EricZimmerman** [comment] 2015-12-21 18:50
can you dump the flags for the key to see if that indicates any additional indicators of how to treat the nk record (SymbolicLink = 0x0010)

sbv-csis, can the hive producing this behavior be shared?

**Comment by sbv-csis** [comment] 2015-12-21 21:58
I'm afraid I can't share the hive raw but i'm currently trying to extract a workable test-case both for this issue as well as for my own tests.
I've recieved the hive via third-party and it's not mine to share. I'm a bit baffled myself as to how the hive got in that condition

How do I access the flags?

**Comment by sbv-csis** [comment] 2015-12-21 22:19
chntpw seems to see the same thing:
```
 chntpw -l bla/software_backup.bin
chntpw version 0.99.6 110511 , (c) Petter N Hagen
Hive <bla/software_backup.bin> name (from header): <emRoot\System32\Config\SOFTWARE>
ROOT KEY at offset: 0x001020 * Subkey indexing type is: 686c <lh>
File size 70254592 [4300000] bytes, containing 14796 pages (+ 1 headerpage)
Used for data: 1134187/67333408 blocks/bytes, unused: 8294/1411424 blocks/bytes.

Simple registry editor. ? for help.

(...)> cd ..

(...)\Microsoft\Windows> cd ..

(...)\Microsoft> cd ..

(...)> cd ..

(...)\Microsoft\Windows> 
```

**Comment by EricZimmerman** [comment] 2015-12-21 22:19
assuming you have a Windows box, try Registry Explorer which is my GUI for viewing hives. it also uses my own c# based parser under the hood, so i would be interested if your hive breaks my code as well

You can get Registry Explorer (and read a ton more about it) here.

http://binaryforay.blogspot.com/p/software.html

You will be interested in the technical view for the key you are trying to view. it will show you a Flags property with each flag decoded to its text representation

you can find out about technical details here

http://binaryforay.blogspot.com/2015/03/registry-explorer-0020-released.html

RECmd would also be useful to test with your data as you would know right away if you have a special hive or the issue is in this project.

**Comment by EricZimmerman** [comment] 2015-12-21 22:20
It could very well be an issue with all tools as i do not recall ever getting a hive with a symlink in it for testing, but please let us know what my tools above give you

**Comment by sbv-csis** [comment] 2015-12-21 22:36
![image](https://cloud.githubusercontent.com/assets/1162544/11943116/a50ae018-a83b-11e5-85ee-7f1357499043.png)

**Comment by EricZimmerman** [comment] 2015-12-21 22:38
can you click on Flags present and then CTRL-C so I can see all the flags?

So did RE process the hive as expected without any errors? from that image it appears to have worked.

if so, the issue is in python-Registry

**Comment by sbv-csis** [comment] 2015-12-21 22:38
HiveEntryRootKey, NoDelete, CompressedName, VirtMirrored

**Comment by EricZimmerman** [comment] 2015-12-21 22:39
ok cool. that should help Willi and NiKiZe out.

**Comment by sbv-csis** [comment] 2015-12-21 22:41
It seems to be working - I'm not really aware what I should be seeing. No infinite loop for sure.

I see lots of "Associated deleted records" and "Unassociated deleted records" otherwise it looks "normal" to me

**Comment by EricZimmerman** [comment] 2015-12-21 22:42
my code recovers and reassociates deleted keys and values in hives. thats what you are seeing. see the user manual and/or the blog posts for all the gory details.

**Comment by sbv-csis** [comment] 2015-12-21 22:45
For now I'll work around the issue with a monkey patch like this:
```
  def path(self):                                                                   
          """                                                                       
          Return the full path of the registry key as a unicode string              
          @return: unicode string containing the path                               
          """                                                                       
          p = self                                                                  
                                                                                    
          name = [p.name()]                                                         
          offsets = set([p._offset])                                                
          while p.has_parent_key():                                                 
              p = p.parent_key()                                                    
              if p._offset in offsets:                                              
                  log.warn('Cyclic path - aborting at %s / %r',                     
                           p.name(), p._offset)                                     
                  break                                                             
              name.append(p.name())                                                 
              offsets.add(p._offset)                                                
          return '\\'.join(reversed(name))                                          
                                                                                    
  Registry.RegistryParse.NKRecord.path = path
```

**Comment by williballenthin** [comment] 2015-12-21 23:17
@sbv-csis, thanks for reporting this issue! Quite a neat hive you've found :-)

@NiKiZe @EricZimmerman thanks for helping to triage :-)

I think the code in the monkey patch above is a pretty good solution. I like that you've used `set` and `'\\'.join(reversed(name))`! Do you mind if I incorporate this code into the main repository?

**Comment by sbv-csis** [comment] 2015-12-22 06:00
It's quite ok. :+1:

**Closed** 2015-12-22 15:22 UTC
